### PR TITLE
2.0 rehash

### PR DESCRIPTION
**Pull request by jamesmartinduffy**

### CODE REVIEW

**Comment by archseer** [comment]
Still no merge? :P Wanted to see the design changes

**Comment by jamesmartinduffy** [comment]
Busy :P

**Comment by jamesmartinduffy** [comment]
image

Just have to finish figuring out what I want to write for the copy.

**Comment by archseer** [comment]
Looks nice! :)

**Comment by archseer** [comment]
Good stuff! :+1:

**Comment by jamesmartinduffy** [comment]
Haha took me long enough to update my job title ;) Still making some tweaks.

**Pull request merged**
